# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker Image CI
on: 
  push: 
    branches: 
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: login to Dockerhub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build the Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/covidtrackingrecord_api .
    - name: Publish to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/covidtrackingrecord_api
